Paulo.Web/ViewModels/Shared/BaseViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Paulo.Web.ViewModels
{
    public class BaseViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Data de Cadastro")]
        public DateTime DataDeCadastro { get; set; }

        [Display(Name = "Data de Atualização")]
        public DateTime? DataDeAtualizacao { get; set; }
        public bool Deleted { get; set; } = false;
    }
}

Paulo.Web/Controllers/LocacaoController.cs
using AutoMapper;
using Microsoft.AspNet.Identity;
using Paulo.Core.Services;
using Paulo.Data.Entities;
using Paulo.Web.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Paulo.Web.Controllers
{
    [Authorize]
    public class LocacaoController : Controller
    {
        private readonly ILocacaoService locacaoService;
        private readonly IFilmeService filmeService;

        public LocacaoController(
            ILocacaoService locacaoService,
            IFilmeService filmeService)
        {
            this.locacaoService = locacaoService;
            this.filmeService = filmeService;
        }

        // GET: Locacao
        public ActionResult Index()
        {
            var locacaoViewModel = Mapper.Map<List<LocacaoViewModel>>(locacaoService.GetAll());

            return View(locacaoViewModel);
        }

        // GET: Locacao/Details/5
        public ActionResult Details(int id)
        {
            var locacaoViewModel = Mapper.Map<LocacaoViewModel>(locacaoService.GetById(id));

            return View(locacaoViewModel);
        }

        // GET: Locacao/Create
        public ActionResult Create()
        {
            var filmesToSelect = Mapper.Map<List<FilmeViewModel>>(filmeService.GetAllToSelect());

            ViewBag.FilmesToSelect = new SelectList(
                filmesToSelect,
                "Id",
                "Nome"
                );

            return View();
        }

        // POST: Locacao/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(LocacaoViewModel locacaoViewModel)
        {
            if (ModelState.IsValid)
            {
                var locacao = Mapper.Map<Locacao>(locacaoViewModel);
                locacaoService.RentFilmes(locacao, locacaoViewModel.SelectedFilmesIds, User.Identity.GetUserId<int>());

                return RedirectToAction("Index");
            }

            return View(locacaoViewModel);
        }

        // GET: Locacao/Edit/5
        public ActionResult Edit(int id)
        {
            var locacaoViewModel = Mapper.Map<LocacaoViewModel>(locacaoService.GetById(id));
            var filmesToSelect = Mapper.Map<List<FilmeViewModel>>(filmeService.GetAllToSelect());
            filmesToSelect.AddRange(locacaoViewModel.Filmes);

            ViewBag.SelectedFilmes = new MultiSelectList(
                filmesToSelect.OrderBy(o => o.Nome).ToList(),
                "Id",
                "Nome",
                locacaoViewModel.Filmes.Select(x => x.Id)
                );

            return View(locacaoViewModel);
        }

        // POST: Locacao/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(LocacaoViewModel locacaoViewModel)
        {
            if (ModelState.IsValid)
            {
                var locacao = Mapper.Map<Locacao>(locacaoViewModel);
                locacaoService.UpdateRentFilmes(locacao.Id, locacaoViewModel.SelectedFilmesIds);

                return RedirectToAction("Index");
            }

            return View(locacaoViewModel);
        }

        // GET: Locacao/Delete/5
        public ActionResult Delete(int id)
        {
            var locacaoViewModel = Mapper.Map<LocacaoViewModel>(locacaoService.GetById(id));

            return View(locacaoViewModel);
        }

        // POST: Locacao/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            locacaoService.Remove(id);

            return RedirectToAction("Index");
        }
    }
}

Paulo.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Locadora</title>
    @Styles.Render("~/bundles/css")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Filme", "Index", "Filme")</li>
                    <li>@Html.ActionLink("Genero", "Index", "Genero")</li>
                    <li>@Html.ActionLink("Locação", "Index", "Locacao")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Locadora</p>
        </footer>
    </div>

    <script src="~/Content/js/jquery-3.3.1.min.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>