Paulo.Web/ViewModels/GeneroViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Paulo.Web.ViewModels
{
    public class GeneroViewModel : BaseViewModel
    {
        [Required(ErrorMessage = "Digite o Nome!")]
        public string Nome { get; set; }
        public bool Ativo { get; set; }

        public List<int> idsToDelete { get; set; }
        public virtual ICollection<FilmeViewModel> Filmes { get; set; }
    }
}

Paulo.Web/Controllers/GeneroController.cs
using AutoMapper;
using Paulo.Core.Services;
using Paulo.Data.Entities;
using Paulo.Web.ViewModels;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Paulo.Web.Controllers
{
    [Authorize]
    public class GeneroController : Controller
    {
        private readonly IGeneroService generoService;

        public GeneroController(IGeneroService generoAppService)
        {
            this.generoService = generoAppService;
        }

        // GET: Genero
        public ActionResult Index()
        {
            var generoViewModel = Mapper.Map<List<GeneroViewModel>>(generoService.GetAll());

            return View(generoViewModel);
        }

        // GET: Genero/Details/5
        public ActionResult Details(int id)
        {
            var generoViewModel = Mapper.Map<GeneroViewModel>(generoService.GetById(id));

            return View(generoViewModel);
        }

        // GET: Genero/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Genero/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(GeneroViewModel generoViewModel)
        {
            if (ModelState.IsValid)
            {
                var genero = Mapper.Map<Genero>(generoViewModel);
                generoService.Add(genero);

                return RedirectToAction("Index");
            }

            return View(generoViewModel);
        }

        // GET: Genero/Edit/5
        public ActionResult Edit(int id)
        {
            var generoViewModel = Mapper.Map<GeneroViewModel>(generoService.GetById(id));

            return View(generoViewModel);
        }

        // POST: Genero/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(GeneroViewModel generoViewModel)
        {
            if (ModelState.IsValid)
            {
                var genero = Mapper.Map<Genero>(generoViewModel);
                generoService.Update(genero);

                return RedirectToAction("Index");
            }

            return View(generoViewModel);
        }

        // GET: Genero/Delete/5
        public ActionResult Delete(int id)
        {
            var generoViewModel = Mapper.Map<GeneroViewModel>(generoService.GetById(id));

            return View(generoViewModel);
        }

        // POST: Genero/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            generoService.Remove(id);

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteMany(List<int> idsToDelete)
        {
            if (ModelState.IsValid)
            {
                if(idsToDelete != null)
                    generoService.RemoveMany(idsToDelete);
            }

            return RedirectToAction("Index");
        }
    }
}

Paulo.Web/Views/Genero/Create.cshtml
@model Paulo.Web.ViewModels.GeneroViewModel

@{
    ViewBag.Title = "Criar";
}

<h2>Criar</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()    
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ativo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.CheckBoxFor(model => model.Ativo, htmlAttributes: new { @class = "no-margin-left", @checked = true })
                    @Html.ValidationMessageFor(model => model.Ativo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para a lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Paulo.Web/Views/Genero/Delete.cshtml
@model Paulo.Web.ViewModels.GeneroViewModel

@{
    ViewBag.Title = "Deletar";
}

<h2>Deletar</h2>

<h3>Tem certeza que deseja deletar este genero?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataDeCadastro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataDeCadastro)
        </dd>

        @if (Model.DataDeAtualizacao.HasValue)
        {
            <dt>
                @Html.DisplayNameFor(model => model.DataDeAtualizacao)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DataDeAtualizacao)
            </dd>
        }

        <dt>
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ativo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Deletar" class="btn btn-default" /> |
            @Html.ActionLink("Voltar para a lista", "Index")
        </div>
    }
</div>

Paulo.Web/Views/Genero/Details.cshtml
@model Paulo.Web.ViewModels.GeneroViewModel

@{
    ViewBag.Title = "Detalhes";
}

<h2>Detalhes</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataDeCadastro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataDeCadastro)
        </dd>

        @if (Model.DataDeAtualizacao.HasValue)
        {
            <dt>
                @Html.DisplayNameFor(model => model.DataDeAtualizacao)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DataDeAtualizacao)
            </dd>
        }

        <dt>
            @Html.DisplayNameFor(model => model.Ativo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ativo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Voltar para a lista", "Index")
</p>

Paulo.Web/Views/Genero/Edit.cshtml
@model Paulo.Web.ViewModels.GeneroViewModel

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.DataDeCadastro)
    @Html.HiddenFor(model => model.DataDeAtualizacao)

    <div class="form-group">
        @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Ativo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.CheckBoxFor(model => model.Ativo, htmlAttributes: new { @class = "no-margin-left" })
                @Html.ValidationMessageFor(model => model.Ativo, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Salvar" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Voltar para a lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Paulo.Web/Views/Genero/Index.cshtml
@model IEnumerable<Paulo.Web.ViewModels.GeneroViewModel>

@{
    ViewBag.Title = "Lista de Generos";
}

<h2>Lista de Generos</h2>

@using (Html.BeginForm("DeleteMany", "Genero", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <p>
        @Html.ActionLink("Criar Novo", "Create", null, htmlAttributes: new { @class = "pull-left" })
    </p>

    if(Model != null & Model.Any())
    {
        <input type="submit" class="btn btn-danger btn-delete pull-right" value="Deletar os selecionados" />
    }

    <table class="table">
        <tr>
            <th>
                Selecionar
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataDeCadastro)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataDeAtualizacao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ativo)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <input type="checkbox" name="idsToDelete" id="idsToDelete" value="@item.Id" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataDeCadastro)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataDeAtualizacao)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ativo)
                </td>
                <td>
                    @Html.ActionLink("Editar", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Detalhes", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Deletar", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>
}